apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: enixdocker1/shoppingapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80    # port inside the container, where your app listens.
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000       # What other pods use to reach this service (K8s NODE forwards external requests to SERVICE)
      targetPort: 80   # Pod's ContainerPort (on which SERVICE will forward request traffic to POD.), (Mostly same as a ContainerPort)
      nodePort: 31000  # External port on the worker node WHICH lets external users sends REQUESTS (30001–32767).