version: '3.9'

services:
  shopping.api:
    image: shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    ports:
      - "8000:80"  # Expose API on localhost:8000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - shopping.db

  shopping.client:
    image: shoppingclient
    build:
      context: .
      dockerfile: Shopping.client/Dockerfile
    ports:
      - "3000:80"  # Assuming the client runs on port 80 inside the container
    depends_on:
      - shopping.api

  shopping.db:
    image: mongo
    ports:
      - "27017:27017"  # Optional: expose for host access
