services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping.client/Dockerfile

  shopping.db:
    image: mongo